sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 145
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 146
      end: 177
      scaling: 0.96
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 178
      end: 285
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 286
      end: 315
      scaling: 0.95
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 316
      end: 387
      scaling: 1.0
      only_FTG: false
      no_FTG: false
