ot_interpolator:
  ros__parameters:
    n_sectors: 3
    yeet_factor: 1.25
    spline_len: 30
    ot_sector_begin: 0.5
    Overtaking_sector0:
      start: 0
      end: 179
      ot_flag: true
    Overtaking_sector1:
      start: 180
      end: 319
      ot_flag: false
    Overtaking_sector2:
      start: 320
      end: 366
      ot_flag: true
