sector_tuner:
  ros__parameters:
    global_limit: 0.8
    n_sectors: 5
    Sector0:
      start: 0
      end: 27
      scaling: 0.68
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 28
      end: 182
      scaling: 0.67
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 183
      end: 287
      scaling: 0.73
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 288
      end: 312
      scaling: 0.64
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 313
      end: 366
      scaling: 0.68
      only_FTG: false
      no_FTG: false
