sector_tuner:
  ros__parameters:
    global_limit: 0.9
    n_sectors: 4
    Sector0:
      start: 0
      end: 147
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 148
      end: 267
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 268
      end: 371
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 372
      end: 372
      scaling: 0.9
      only_FTG: false
      no_FTG: false
