sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 7
    Sector0:
      start: 0
      end: 25
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 26
      end: 90
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 91
      end: 163
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 164
      end: 207
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 208
      end: 325
      scaling: 0.97
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 326
      end: 343
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 344
      end: 428
      scaling: 0.92
      only_FTG: false
      no_FTG: false
