sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 74
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 75
      end: 140
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 141
      end: 185
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 186
      end: 293
      scaling: 0.97
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 294
      end: 313
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 314
      end: 387
      scaling: 0.92
      only_FTG: false
      no_FTG: false
