sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 73
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 74
      end: 139
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 140
      end: 206
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 207
      end: 291
      scaling: 0.96
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 292
      end: 309
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 310
      end: 377
      scaling: 0.92
      only_FTG: false
      no_FTG: false
