sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 90
      scaling: 0.85
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 91
      end: 144
      scaling: 0.85
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 145
      end: 271
      scaling: 0.85
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 272
      end: 425
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 426
      end: 462
      scaling: 0.88
      only_FTG: false
      no_FTG: false
