sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 75
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 76
      end: 143
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 144
      end: 197
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 198
      end: 281
      scaling: 0.94
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 282
      end: 308
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 309
      end: 388
      scaling: 0.92
      only_FTG: false
      no_FTG: false
