ot_interpolator:
  ros__parameters:
    n_sectors: 3
    yeet_factor: 1.25
    spline_len: 30
    ot_sector_begin: 0.5
    Overtaking_sector0:
      start: 0
      end: 192
      ot_flag: true
    Overtaking_sector1:
      start: 193
      end: 371
      ot_flag: true
    Overtaking_sector2:
      start: 372
      end: 372
      ot_flag: true
