sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 118
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 119
      end: 214
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 215
      end: 289
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 290
      end: 371
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 372
      end: 372
      scaling: 0.9
      only_FTG: false
      no_FTG: false
