sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 4
    Sector0:
      start: 0
      end: 105
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 106
      end: 227
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 228
      end: 299
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 300
      end: 378
      scaling: 1.0
      only_FTG: false
      no_FTG: false
