sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 149
      scaling: 1.0 #0.87
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 150
      end: 194
      scaling: 0.95 #0.88
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 195
      end: 295
      scaling: 1.0 #0.93
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 296
      end: 330
      scaling: 0.92 #0.84
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 331
      end: 394
      scaling: 0.95 #0.88
      only_FTG: false
      no_FTG: false
