sector_tuner:
  ros__parameters:
    global_limit: 0.8
    n_sectors: 5
    Sector0:
      start: 0
      end: 149
      scaling: 0.7
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 150
      end: 194
      scaling: 0.68
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 195
      end: 295
      scaling: 0.72
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 296
      end: 330
      scaling: 0.66
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 331
      end: 394
      scaling: 0.68
      only_FTG: false
      no_FTG: false
