sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 78
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 79
      end: 143
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 144
      end: 204
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 205
      end: 282
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 283
      end: 307
      scaling: 0.93
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 308
      end: 390
      scaling: 0.94
      only_FTG: false
      no_FTG: false
