sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 101
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 102
      end: 177
      scaling: 0.93
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 178
      end: 277
      scaling: 0.95
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 278
      end: 316
      scaling: 0.89
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 317
      end: 387
      scaling: 0.95
      only_FTG: false
      no_FTG: false
