STATE:
  - VX
  - VY
  - YAW_RATE
  - STEERING_FB
ACTIONS:
  - STEERING_CMD
  - VREF
PARAMETERS:
  - Bf: 
  - Cf: 
  - Df: 
  - Ef:
  - Br: 
  - Cr: 
  - Dr:
  - Er:
  - Frx:
VEHICLE_SPECS:
  lf: 0.15875
  lr: 0.17145
  mass: 3.74
  Iz: 0.04712
MODEL:
  NAME: DeepPacejkaF110
  HORIZON: 16
  LAYERS:
    - GRU:
      OUT_FEATURES: 256
      LAYERS: 5
    - DENSE:
      OUT_FEATURES: 254
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 128
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.000439
