STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf:
    Min: 5.0
    Max: 30.0
  - Cf:
    Min: 0.5
    Max: 2.0
  - Df:
    Min: 0.1
    Max: 0.9
  - Ef:
    Min: -2.0
    Max: 0.0
  - Br:
    Min: 5.0
    Max: 30.0
  - Cr:
    Min: 0.5
    Max: 2.0
  - Dr:
    Min: 0.1
    Max: 0.9
  - Er:
    Min: -2.0
    Max: 0.0
  - Cm1:
    Min: 0.1435
    Max: 0.574
  - Cm2:
    Min: 0.02725
    Max: 0.109
  - Cr0:
    Min: 0.0259
    Max: 0.1036
  - Cr2:
    Min: 1.75e-4
    Max: 7.0e-4
  - Iz:
    Min: 1.39e-5
    Max: 5.56e-5
  - Shf:
    Min: -0.02
    Max: 0.02
  - Svf:
    Min: -0.003
    Max: 0.003
  - Shr:
    Min: -0.02
    Max: 0.02
  - Svr:
    Min: -0.003
    Max: 0.003
# VEHICLE_SPECS:
#   lf: 0.029
#   lr: 0.033
#   mass: 0.041
VEHICLE_SPECS:
  lf: 0.15875
  lr: 0.17145
  mass: 3.74
MODEL:
  NAME: DeepDynamics
  HORIZON: 5
  LAYERS:
    - GRU:
      OUT_FEATURES: 25
      LAYERS: 7
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 436
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 32
    NUM_EPOCHS: 400
    OPTIMIZER: Adam
    LR: 0.0006
