sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 73
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 74
      end: 137
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 138
      end: 218
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 219
      end: 293
      scaling: 0.94
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 294
      end: 315
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 316
      end: 387
      scaling: 0.92
      only_FTG: false
      no_FTG: false
