sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 76
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 77
      end: 143
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 144
      end: 182
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 183
      end: 276
      scaling: 0.97
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 277
      end: 302
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 303
      end: 385
      scaling: 0.92
      only_FTG: false
      no_FTG: false
