sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 7
    Sector0:
      start: 0
      end: 34
      scaling: 0.88
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 35
      end: 105
      scaling: 0.88
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 106
      end: 169
      scaling: 0.89
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 170
      end: 224
      scaling: 0.88
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 225
      end: 329
      scaling: 0.95
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 330
      end: 361
      scaling: 0.89
      only_FTG: false
      no_FTG: false
    Sector6:
      start: 362
      end: 420
      scaling: 0.9
      only_FTG: false
      no_FTG: false
