sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 79
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 80
      end: 142
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 143
      end: 220
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 221
      end: 286
      scaling: 0.95
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 287
      end: 305
      scaling: 0.89
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 306
      end: 381
      scaling: 0.9
      only_FTG: false
      no_FTG: false
