sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 77
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 78
      end: 144
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 145
      end: 211
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 212
      end: 283
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 284
      end: 307
      scaling: 0.93
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 308
      end: 390
      scaling: 0.94
      only_FTG: false
      no_FTG: false
