sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 6
    Sector0:
      start: 0
      end: 75
      scaling: 0.9
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 76
      end: 141
      scaling: 0.92
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 142
      end: 212
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 213
      end: 302
      scaling: 0.95
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 303
      end: 322
      scaling: 0.91
      only_FTG: false
      no_FTG: false
    Sector5:
      start: 323
      end: 387
      scaling: 0.92
      only_FTG: false
      no_FTG: false
